version: '2.1'

services:
  node:
    image: ghcr.io/wouterds/movie-search-cdn-caching-example
    restart: unless-stopped
    mem_limit: 64mb
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.devcraftzingmovieapi.redirectscheme.scheme=https"
      - "traefik.http.routers.devcraftzingmovieapi-http.rule=Host(`movie-api.craftzing.dev`)"
      - "traefik.http.routers.devcraftzingmovieapi-http.entrypoints=web"
      - "traefik.http.routers.devcraftzingmovieapi-http.middlewares=devcraftzingmovieapi"
      - "traefik.http.routers.devcraftzingmovieapi.rule=Host(`movie-api.craftzing.dev`)"
      - "traefik.http.routers.devcraftzingmovieapi.entrypoints=websecure"
      - "traefik.http.routers.devcraftzingmovieapi.tls.certresolver=myhttpchallenge"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
