version: '2.1'

services:
  node:
    image: ghcr.io/wouterds/movie-search-api
    restart: unless-stopped
    mem_limit: 64mb
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.devcraftzingmoviesearchapi.redirectscheme.scheme=https"
      - "traefik.http.routers.devcraftzingmoviesearchapi-http.rule=Host(`movie-search-api.craftzing.dev`)"
      - "traefik.http.routers.devcraftzingmoviesearchapi-http.entrypoints=web"
      - "traefik.http.routers.devcraftzingmoviesearchapi-http.middlewares=devcraftzingmoviesearchapi"
      - "traefik.http.routers.devcraftzingmoviesearchapi.rule=Host(`movie-search-api.craftzing.dev`)"
      - "traefik.http.routers.devcraftzingmoviesearchapi.entrypoints=websecure"
      - "traefik.http.routers.devcraftzingmoviesearchapi.tls.certresolver=myhttpchallenge"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
